### ISSUE TITLE
Load models like environments

### ISSUE THREAD

**Issue by mryellow** [Kaixhin/Atari#51]
Currently models are loaded by checking for file existing on the provided path. If a class name is given this check will fail as `paths.filep` doesn't check `LUA_PATH`. Handling this like environments will add some consistency and allow users to more easily store their models in external repositories.

https://github.com/Kaixhin/Atari/blob/1e48018a2e1e25895d6ac851b5de058125e7b5e2/Model.lua#L73

Will put together a PR where Atari and Catch models are placed in separate files and `modelBody` is setup in the same way `env` is currently.

**Comment by mryellow** [comment]
https://github.com/Kaixhin/Atari/pull/52

Look okay? Any reasons why bodies would need to be flat without a class wrapping them?

Passing `self` allowing the `modelBody` class to access any properties it might need from `Model` without creating an extra property passing down all the `opts`.

Works well with external models stored in my `rlenvs` repo. Accessed with path `LUA_PATH="$LUA_PATH;/home/user/dqn-envs/?.lua"`. Where `?` is matches either `rlenvs/Env` or `models/Model`.

**Comment by Kaixhin** [comment]
Flat files are simpler, but I can't think of any other reason to keep them. PR makes sense.
