### ISSUE TITLE
problem in Agent.lua

### ISSUE THREAD

**Issue by Hislocked** [Kaixhin/Atari#55]
I have ran the default experiment like 
`th main.lua`
when it comes to the 50000th episode, it tells me that in Agent.lua 359 line
`self.tdErr = torch.max(torch.cat(tdErrAL, self.tdErr:csub((self.VPrime:csub(QPrime):mul(self.PALpha))), 3), 3):view(N, 1)`
the input of `:view` is 32 \* 10 \* 1 while the output is 32*1

so I change the code like `:view(N , 10 , 1)`

is that OK or I do the wrong thing?

**Comment by Kaixhin** [comment]
The bug is fixed, but for future reference there are many options available, so it's best to look at `run.sh` for good configurations.
