### ISSUE TITLE
gnuplots memory unreleased

### ISSUE THREAD

**Issue by nadavbh12** [Kaixhin/Atari#58]
The gnuplots created by the simulations stay in the RAM as long as the simulation is running, effectively acting as a memory leak.
Item already appears in a [TODO comment.](https://github.com/Kaixhin/Atari/blob/52044699c09dad3b53358b94f3042bfe1c8ba46f/async/ValidationAgent.lua#L257)

**Comment by Kaixhin** [comment]
Decided to have a quick look, and maybe https://github.com/torch/gnuplot/issues/15 is the solution? Could you try adding `gnuplot.close()` to the end of the `plotValidation` function and see if this solves the issue?
