### ISSUE TITLE
Partition number and segments

### ISSUE THREAD

**Issue by ColdCodeCool** [Kaixhin/Atari#63]
@Kaixhin Thank you for your excellent work!

I did not quite understand why partition number is not the same as segments number k, which is the batch size suggested in the PER paper, in your implementation.  Could you please help me understand this?

**Comment by Kaixhin** [comment]
The segments number, k, is used for stratified sampling for constructing a minibatch, as you've noted. The partition number, which is a number that I chose myself, and is based on this note from the appendix of the paper:
> A small improvement in running time came from avoiding excessive recalculation of partitions for the sampling distribution. We reused the same partition for values of N that are close together and by updating α and β infrequently.

For rank-based PER, N obviously changes as the agent starts and picks up enough memories to fill its replay memory. Once it is full then the partitions don't change, as the buffer replaces old transitions with new ones and N is then static. But with N = 1000000, it'd be expensive to recalculate the indices needed for stratified sampling every time a new transition was added. Thus it should be done a few times until the memory is full. Whether 100 times is the appropriate rate or not, I'm not sure (as it's not given in the paper).
