### ISSUE TITLE
actor-critic based

### ISSUE THREAD

**Issue by Tord-Zhang** [Kaixhin/Atari#65]
I look through the code and find that it seems the A3C algorithm has not been implemented?Will you release the A3C code based on Torch?

**Comment by Kaixhin** [comment]
The A3C agent is implemented [here](https://github.com/Kaixhin/Atari/blob/master/async/A3CAgent.lua). If you use the [`run.sh` script](https://github.com/Kaixhin/Atari/blob/master/run.sh) you will see one preconfigured option for running A3C with Catch and another for running A3C with Atari games.

**Comment by Tord-Zhang** [comment]
thank your so much for your response.I just read the code,and found that only policy work(critic) is trained and updated,while the value work is untrained.Maybe I got some misunderstandings about A3C?Shouldn't actor be trained?
